package com.toolnexa.app

data class PhoneCountry(
    val name: String,
    val code: String,
    val flag: String
)

object PhoneCountries {
    val all = listOf(
        PhoneCountry("Moçambique", "+258", "🇲🇿"),
        PhoneCountry("África do Sul", "+27", "🇿🇦"),
        PhoneCountry("Angola", "+244", "🇦🇴"),
        PhoneCountry("Brasil", "+55", "🇧🇷"),
        PhoneCountry("Portugal", "+351", "🇵🇹"),
        PhoneCountry("Estados Unidos", "+1", "🇺🇸"),
        PhoneCountry("Canadá", "+1", "🇨🇦"),
        PhoneCountry("Reino Unido", "+44", "🇬🇧"),
        PhoneCountry("França", "+33", "🇫🇷"),
        PhoneCountry("Alemanha", "+49", "🇩🇪"),
        PhoneCountry("Espanha", "+34", "🇪🇸"),
        PhoneCountry("Itália", "+39", "🇮🇹"),
        PhoneCountry("Países Baixos", "+31", "🇳🇱"),
        PhoneCountry("Bélgica", "+32", "🇧🇪"),
        PhoneCountry("Suíça", "+41", "🇨🇭"),
        PhoneCountry("Irlanda", "+353", "🇮🇪"),
        PhoneCountry("Austrália", "+61", "🇦🇺"),
        PhoneCountry("Nova Zelândia", "+64", "🇳🇿"),
        PhoneCountry("Índia", "+91", "🇮🇳"),
        PhoneCountry("Paquistão", "+92", "🇵🇰"),
        PhoneCountry("Bangladesh", "+880", "🇧🇩"),
        PhoneCountry("Emirados Árabes Unidos", "+971", "🇦🇪"),
        PhoneCountry("Arábia Saudita", "+966", "🇸🇦"),
        PhoneCountry("Israel", "+972", "🇮🇱"),
        PhoneCountry("Turquia", "+90", "🇹🇷"),
        PhoneCountry("Egito", "+20", "🇪🇬"),
        PhoneCountry("Nigéria", "+234", "🇳🇬"),
        PhoneCountry("Quénia", "+254", "🇰🇪"),
        PhoneCountry("Tanzânia", "+255", "🇹🇿"),
        PhoneCountry("Uganda", "+256", "🇺🇬"),
        PhoneCountry("Zâmbia", "+260", "🇿🇲"),
        PhoneCountry("Zimbabué", "+263", "🇿🇼"),
        PhoneCountry("Malawi", "+265", "🇲🇼"),
        PhoneCountry("Namíbia", "+264", "🇳🇦"),
        PhoneCountry("Botswana", "+267", "🇧🇼"),
        PhoneCountry("Ruanda", "+250", "🇷🇼"),
        PhoneCountry("Gana", "+233", "🇬🇭"),
        PhoneCountry("Etiópia", "+251", "🇪🇹"),
        PhoneCountry("Marrocos", "+212", "🇲🇦"),
        PhoneCountry("Argélia", "+213", "🇩🇿"),
        PhoneCountry("Tunísia", "+216", "🇹🇳"),
        PhoneCountry("China", "+86", "🇨🇳"),
        PhoneCountry("Japão", "+81", "🇯🇵"),
        PhoneCountry("Coreia do Sul", "+82", "🇰🇷"),
        PhoneCountry("Indonésia", "+62", "🇮🇩"),
        PhoneCountry("Malásia", "+60", "🇲🇾"),
        PhoneCountry("Singapura", "+65", "🇸🇬"),
        PhoneCountry("Filipinas", "+63", "🇵🇭"),
        PhoneCountry("Tailândia", "+66", "🇹🇭"),
        PhoneCountry("Vietname", "+84", "🇻🇳"),
        PhoneCountry("Rússia", "+7", "🇷🇺"),
        PhoneCountry("Ucrânia", "+380", "🇺🇦"),
        PhoneCountry("Polónia", "+48", "🇵🇱"),
        PhoneCountry("Suécia", "+46", "🇸🇪"),
        PhoneCountry("Noruega", "+47", "🇳🇴"),
        PhoneCountry("Dinamarca", "+45", "🇩🇰"),
        PhoneCountry("Finlândia", "+358", "🇫🇮"),
        PhoneCountry("Grécia", "+30", "🇬🇷"),
        PhoneCountry("México", "+52", "🇲🇽"),
        PhoneCountry("Argentina", "+54", "🇦🇷"),
        PhoneCountry("Chile", "+56", "🇨🇱"),
        PhoneCountry("Colômbia", "+57", "🇨🇴"),
        PhoneCountry("Peru", "+51", "🇵🇪"),
        PhoneCountry("Venezuela", "+58", "🇻🇪")
    )
}
